# Build Geth in a stock Go builder container
FROM golang:1.15-buster as builder

RUN apt-get update && apt-get install -y make gcc musl-dev git

ADD ./l2geth /go-ethereum
RUN cd /go-ethereum && make geth

# Pull Geth into a second stage deploy alpine container
FROM ubuntu:21.10

RUN apt-get update && apt-get install -y ca-certificates jq curl
COPY --from=builder /go-ethereum/build/bin/geth /usr/local/bin/

EXPOSE 8545 8546 8547
COPY ./ops/scripts/geth-peer.sh .
ENTRYPOINT ["geth"]
